import { defineConfig } from 'astro/config';
import remarkMath from 'remark-math';
import remarkFootnoteIndent from './src/plugins/remark-footnote-indent.mjs';
import rehypeKatex from 'rehype-katex';
import rehypeMark from './src/plugins/rehype-mark.mjs';
import rehypePopover from './src/plugins/rehype-popover.mjs';
import rehypeTableWrap from './src/plugins/rehype-table-wrap.mjs';

export default defineConfig({
  base: process.env.SITE_BASE || '/',
  vite: { server: { strictPort: true } },
  markdown: {
    remarkPlugins: [remarkFootnoteIndent, remarkMath],
    rehypePlugins: [rehypeKatex, rehypeMark, rehypeTableWrap, rehypePopover],
  },
  build: {
    format: 'directory',
  },
  redirects: {
    '/': '/notes/',
    '/blog/': '/knowledge/',
    '/prompts/': '/knowledge/',
    '/knowledge/personal-blog-setup/': '/knowledge/personal-blog-building-practice/',
    '/blog/personal-blog-setup/': '/knowledge/personal-blog-building-practice/',
    '/knowledge/how-to-stop-model-laziness/': '/knowledge/tips-collection/',
    '/prompts/how-to-stop-model-laziness/': '/knowledge/tips-collection/',
    '/knowledge/操作系统入门/': '/knowledge/operating-systems-fundamentals/',
    '/blog/操作系统入门/': '/knowledge/operating-systems-fundamentals/',
    '/knowledge/操作系统基础知识/': '/knowledge/operating-systems-fundamentals/',
    '/blog/操作系统基础知识/': '/knowledge/operating-systems-fundamentals/',
    '/knowledge/全栈详解/': '/knowledge/traditional-full-stack-development-overview/',
    '/blog/全栈详解/': '/knowledge/traditional-full-stack-development-overview/',
    '/knowledge/full-stack-development/': '/knowledge/traditional-full-stack-development-overview/',
    '/blog/full-stack-development/': '/knowledge/traditional-full-stack-development-overview/',
    '/knowledge/产品形态与技术栈/': '/knowledge/traditional-full-stack-development-overview/',
    '/blog/产品形态与技术栈/': '/knowledge/traditional-full-stack-development-overview/',
    '/knowledge/product-stack/': '/knowledge/traditional-full-stack-development-overview/',
    '/blog/product-stack/': '/knowledge/traditional-full-stack-development-overview/',
    '/knowledge/论文阅读心得/': '/knowledge/paper-reading-methods-overview/',
    '/blog/论文阅读心得/': '/knowledge/paper-reading-methods-overview/',
    '/knowledge/小组会-世界模型/': '/knowledge/world-model-overview/',
    '/blog/小组会-世界模型/': '/knowledge/world-model-overview/',

    // Preserve the previous English URLs after title-based slug renaming.
    '/knowledge/personal-blog-building-guide/': '/knowledge/personal-blog-building-practice/',
    '/blog/personal-blog-building-guide/': '/knowledge/personal-blog-building-practice/',
    '/knowledge/dashboard-building-guide/': '/knowledge/dashboard-building-practice/',
    '/blog/dashboard-building-guide/': '/knowledge/dashboard-building-practice/',
    '/knowledge/how-to-make-picture/': '/knowledge/professional-chart-creation-practice/',
    '/blog/how-to-make-picture/': '/knowledge/professional-chart-creation-practice/',
    '/knowledge/how-to-make-ppt-with-agent/': '/knowledge/agent-ppt-creation-practice/',
    '/blog/how-to-make-ppt-with-agent/': '/knowledge/agent-ppt-creation-practice/',
    '/knowledge/traditional-ppt-method/': '/knowledge/traditional-ppt-creation-practice/',
    '/blog/traditional-ppt-method/': '/knowledge/traditional-ppt-creation-practice/',
    '/knowledge/pure-frontend-dev/': '/knowledge/pure-frontend-web-development-practice/',
    '/blog/pure-frontend-dev/': '/knowledge/pure-frontend-web-development-practice/',
    '/knowledge/research-to-video/': '/knowledge/research-to-video-practice/',
    '/blog/research-to-video/': '/knowledge/research-to-video-practice/',
    '/knowledge/opencode-model-routing/': '/knowledge/opencode-model-routing-config/',
    '/blog/opencode-model-routing/': '/knowledge/opencode-model-routing-config/',
    '/knowledge/markdown-syntax-introduction/': '/knowledge/markdown-fundamentals/',
    '/blog/markdown-syntax-introduction/': '/knowledge/markdown-fundamentals/',
    '/knowledge/development-style/': '/knowledge/development-style-fundamentals/',
    '/blog/development-style/': '/knowledge/development-style-fundamentals/',
    '/knowledge/operating-systems-introduction/': '/knowledge/operating-systems-fundamentals/',
    '/blog/operating-systems-introduction/': '/knowledge/operating-systems-fundamentals/',
    '/knowledge/data-structures-introduction/': '/knowledge/data-structures-fundamentals/',
    '/blog/data-structures-introduction/': '/knowledge/data-structures-fundamentals/',
    '/knowledge/algorithms-introduction/': '/knowledge/algorithms-fundamentals/',
    '/blog/algorithms-introduction/': '/knowledge/algorithms-fundamentals/',
    '/knowledge/computer-networks-introduction/': '/knowledge/computer-networks-fundamentals/',
    '/blog/computer-networks-introduction/': '/knowledge/computer-networks-fundamentals/',
    '/knowledge/traditional-full-stack-development/': '/knowledge/traditional-full-stack-development-overview/',
    '/blog/traditional-full-stack-development/': '/knowledge/traditional-full-stack-development-overview/',
    '/knowledge/awesome-chores/': '/knowledge/task-collection/',
    '/blog/awesome-chores/': '/knowledge/task-collection/',
    '/knowledge/awesome-blogs/': '/knowledge/blog-collection/',
    '/blog/awesome-blogs/': '/knowledge/blog-collection/',
    '/knowledge/awesome-tricks/': '/knowledge/tips-collection/',
    '/blog/awesome-tricks/': '/knowledge/tips-collection/',
    '/knowledge/awesome-skills/': '/knowledge/skills-collection/',
    '/blog/awesome-skills/': '/knowledge/skills-collection/',
    '/knowledge/awesome-rules/': '/knowledge/rules-collection/',
    '/blog/awesome-rules/': '/knowledge/rules-collection/',
    '/knowledge/hello-world/': '/knowledge/2026-07-19-devnotes-first-post/',
    '/blog/hello-world/': '/knowledge/2026-07-19-devnotes-first-post/',
    '/knowledge/birthday-letter-2026/': '/knowledge/2026-07-29-fourth-birthday-together/',
    '/blog/birthday-letter-2026/': '/knowledge/2026-07-29-fourth-birthday-together/',
    '/knowledge/thought-0803/': '/knowledge/2026-08-03-attention-habits-development-taxonomy/',
    '/blog/thought-0803/': '/knowledge/2026-08-03-attention-habits-development-taxonomy/',
    '/knowledge/thought-0804/': '/knowledge/2026-08-04-igarss-video-recording/',
    '/blog/thought-0804/': '/knowledge/2026-08-04-igarss-video-recording/',
    '/knowledge/world-models/': '/knowledge/world-model-overview/',
    '/blog/world-models/': '/knowledge/world-model-overview/',
    '/knowledge/llm-training-paradigm/': '/knowledge/llm-training-paradigm-overview/',
    '/blog/llm-training-paradigm/': '/knowledge/llm-training-paradigm-overview/',
    '/knowledge/paper-reading/': '/knowledge/paper-reading-methods-overview/',
    '/blog/paper-reading/': '/knowledge/paper-reading-methods-overview/',
    '/prompts/how-to-make-picture/': '/knowledge/professional-chart-creation-practice/',
    '/prompts/pure-frontend-dev/': '/knowledge/pure-frontend-web-development-practice/',
    '/prompts/how-to-make-ppt-with-agent/': '/knowledge/agent-ppt-creation-practice/',
    '/prompts/research-to-video/': '/knowledge/research-to-video-practice/',
    '/prompts/awesome-tricks/': '/knowledge/tips-collection/',
  },
});
